### ISSUE TITLE
Support namespaced modules in package importer

### ISSUE THREAD

**Issue by armpogart** [maoberlehner/node-sass-magic-importer#163] opened 2018-03-06 15:11 UTC
As far as I see `package-importer` doesn't support importing from namespaced packages.
I have package, that is in it's own namespace in `node_modules`, something like `node_modules/@namespace/package`.
If I specify the file to import as `@import '~@namespace/package/dist/css/style'` I get `Error: File to import not found or unreadable`, if I try to import `@import '~@namespace/package/dist/css/style.css'` I get just `import` statement in final css.

**Comment by maoberlehner** [comment] 2018-03-06 17:26
Hey @armpogart 

namespaced packages should work with `node-sass-package-importer`. I myself use this package heavily with my own SCSS framework [avalanche](https://avalanche.oberlehner.net/) which is also using namespaces.

I've just added a test for namespaced packages in combination with CSS: https://github.com/maoberlehner/node-sass-magic-importer/commit/dfc0955e82d5be3842281cba693240cc01a8e8b0 which works as expected.

So I think there must be some other problem. Can you tell me more about your build setup?

**Comment by armpogart** [comment] 2018-03-15 19:20
Simplified example (minimum test case):
I have following directory structure:
````
src
  styles
    main.scss
````
`main.scss`:
````scss
@import "~@fengyuanchen/datepicker/dist/datepicker.css";
````
`package.json`:
````json
{
  "name": "test-kit",
  "dependencies": {
    "@fengyuanchen/datepicker": "^0.6.4",
    "bootstrap": "^4.0.0"
  },
  "devDependencies": {
    "gulp": "4.0.0",
    "gulp-cli": "^2.0.1",
    "gulp-sass": "^3.1.0",
    "node-sass-magic-importer": "^5.1.0"
  }
}
````
`gulpfile.js`:
````js
const gulp = require('gulp');

// Gulp Plugins
const sass = require('gulp-sass');
const magicImporter = require('node-sass-magic-importer');

gulp.task('styles', () => {
  return gulp.src('./src/styles/main.scss')
      .pipe(sass({
          importer: magicImporter(),
          precision: 8,
      }).on('error', function(err) {
          sass.logError(err);
      }))
      .pipe(gulp.dest('./dist'));
});
````
Running `gulp styles` I get following compiled css file:
````css
@import url(~@fengyuanchen/datepicker/dist/datepicker.css);
````
The problem is easily replicated with the mentioned setup.
Also is it correct behavior, that if I don't specify css extension in import, such as `@import "~@fengyuanchen/datepicker/dist/datepicker.css";` I get error which is I think from the fact that it tries to import `datepicker.js` file which in the same directory and not the css.

**Comment by maoberlehner** [comment] 2018-03-17 16:22
Thank you for providing this detailed informations. Unfortunately, I still can't reproduce 🤔

I've set up everything exactly the same, when I run `npx gulp styles` a file `dist/main.css` with the contents of the datepicker CSS file is created.

The only thing you didn't mention is how to you run the gulp task? My guess is, that you're running the gulp task in a way that `process.cwd()` is not the directory in which the `node_modules` directory is located, which is why `node-sass-magic-importer` can't find the package.

**Comment by maoberlehner** [comment] 2018-07-05 16:30
Closing because I can't reproduce and no additional informations were provided. Please open a new issue if this is still an issue.

**Closed by maoberlehner** 2018-07-05 16:30 UTC
