### ISSUE TITLE
glob importing doesn't ignore partials

### ISSUE THREAD

**Issue by sebnitu** [maoberlehner/node-sass-magic-importer#157] opened 2017-12-06 23:35 UTC
I'm trying to glob import a bunch of files from a directory and I'm getting some weird behavior. My component structure looks like this:

```
src/
  blocks/
    menu/
      _menu_stack.scss
      menu.scss
    file-1.scss
    file-2.scss
    file-3.scss
imports.scss
```

## Case 1

Inside of imports, I have:
```
@import 'blocks/**/*';
```

What I expect this to do is to get all `.scss` files from the blocks directory and all it's sub directories. Instead, I get this error:

```
Error in plugin 'sass'
Message:
    blocks/**/*
Error: File to import not found or unreadable: .../src/blocks/menu.
       Parent style sheet: blocks/**/*
        on line 16 of blocks/**/*
>> @import '.../src/blocks/menu';
   ^
```

Which I think it means it's trying to import the directory itself and not the files inside it, right?

## Case 2

So instead, I explicitly make the import look for `.scss`

```
@import 'blocks/**/*.scss';
```

Which gives me this error:

```
Error in plugin 'sass'
Message:
    src/blocks/menu/_menu_stack.scss
Error: Undefined variable: "$menu-indent".
        on line 12 of src/blocks/menu/_menu_stack.scss
>>     margin-left: $menu-indent;
   -----------------^
```

Which means it's not ignoring partials and trying to import them as well. 

## Case 3

So my final attempt was to manually write the exclude for partials in the import.

```
@import 'blocks/**/*.scss!(_*.scss)';
```

But this gives me the same error as case 2 and it still tries to import the partials:

```
Error in plugin 'sass'
Message:
    src/blocks/menu/_menu_stack.scss
Error: Undefined variable: "$menu-indent".
        on line 12 of src/blocks/menu/_menu_stack.scss
>>     margin-left: $menu-indent;
   -----------------^
```

Is this a bug or am I doing things wrong?

**Comment by maoberlehner** [comment] 2017-12-07 04:18
Thank you for your detailed bug report.

**Case 1** is odd, I'll look into this.
**Case 2** is the expected behavior – node-sass-glob-importer just imports everything thats matched by the given glob pattern
**Case 3** should be in the right direction, I'll look into this, why it doesn't work

**Comment by maoberlehner** [comment] 2017-12-07 04:32
Could you maybe try this: `src/blocks/**/[!_]*.scss`?

You can use this tool to check glob patterns: http://www.globtester.com/#p=eJwrLkrWT8rJT84u1tfS0o9WjI%2FV0itOLi4GAGYQB%2FQ%3D&r=eJzFkEEOgjAURK%2FSdKWJ0ICbAqVXIaUWbSgt6a9GPb0gLiQsiHHBZlZ%2FZt4fdtI3JI0AKHEngrxgDl6S2jjZAumUvZJq1AqCkG0MEoDVnjPohUUQHkaVuHE2RKCfKkdJFqf9vViGjDK5yWjl7xAylHP2RYDnwdIZ53Pkz%2FWOpgeUUDpIRvcFWqmseuGDFmbWuIY8IU23C7LPNr%2F83WijomR7hHR7hON%2FCC8J2uVo&

Although it doesn't work with the pattern I provided, but it could be, that it handles `_` in a weird way, because with other characters than `_` the pattern works 🤔

**Comment by sebnitu** [comment] 2017-12-07 05:12
Ok, so I just tried:

```
@import 'blocks/**/[!_]*.scss';
```

and this is the error I got:

```
/Users/sebnitu/Documents/Sites/sandbox/vrembem/node_modules/postcss/lib/lazy-result.js:273
            throw error;
            ^

TypeError: Cannot read property 'some' of undefined
    at extractNodeRecursively (/Users/sebnitu/Documents/Sites/sandbox/vrembem/node_modules/css-node-extract/dist/lib/extract-node-recursively.js:8:18)
    at filterNamesArray.some (/Users/sebnitu/Documents/Sites/sandbox/vrembem/node_modules/css-node-extract/dist/lib/postcss-node-extract.js:15:30)
    at Array.some (<anonymous>)
    at nodes.walk (/Users/sebnitu/Documents/Sites/sandbox/vrembem/node_modules/css-node-extract/dist/lib/postcss-node-extract.js:13:30)
    at /Users/sebnitu/Documents/Sites/sandbox/vrembem/node_modules/postcss/lib/container.js:144:26
    at Root.each (/Users/sebnitu/Documents/Sites/sandbox/vrembem/node_modules/postcss/lib/container.js:110:22)
    at Root.walk (/Users/sebnitu/Documents/Sites/sandbox/vrembem/node_modules/postcss/lib/container.js:143:21)
    at /Users/sebnitu/Documents/Sites/sandbox/vrembem/node_modules/css-node-extract/dist/lib/postcss-node-extract.js:11:15
    at LazyResult.run (/Users/sebnitu/Documents/Sites/sandbox/vrembem/node_modules/postcss/lib/lazy-result.js:270:20)
    at LazyResult.sync (/Users/sebnitu/Documents/Sites/sandbox/vrembem/node_modules/postcss/lib/lazy-result.js:257:32)
    at LazyResult.stringify (/Users/sebnitu/Documents/Sites/sandbox/vrembem/node_modules/postcss/lib/lazy-result.js:281:14)
    at LazyResult.get (/Users/sebnitu/Documents/Sites/sandbox/vrembem/node_modules/postcss/lib/lazy-result.js:330:25)
    at Object.exports.processSync (/Users/sebnitu/Documents/Sites/sandbox/vrembem/node_modules/css-node-extract/dist/index.js:10:45)
    at Object.importer (/Users/sebnitu/Documents/Sites/sandbox/vrembem/node_modules/node-sass-magic-importer/dist/index.js:99:51)
    at options.importer (/Users/sebnitu/Documents/Sites/sandbox/vrembem/node_modules/node-sass/lib/index.js:336:31)
```

**Comment by sebnitu** [comment] 2017-12-07 05:12
Here's something else that's kind of interesting. I reverted the import back to:

```
@import 'blocks/**/*.scss';
```

But this time, I took the none-partial menu file and put it in the root of the blocks directory and it compiled with no problems!

```
src/
  blocks/
    menu/
      _menu_stack.scss
    menu.scss <--- moved this out of menu and into blocks
    file-1.scss
    file-2.scss
    file-3.scss
imports.scss
```

In this case, it didn't try try importing the partials inside of the menu directory.

You can see my example here: https://github.com/sebnitu/vrembem/tree/master/src

**Comment by maoberlehner** [comment] 2017-12-07 05:26
Ok, thanks I'll checkout your repository to further look into this later this day. Thanks for giving me so much details to work with. This makes debugging a lot easier.

**Comment by maoberlehner** [comment] 2017-12-08 16:35
@sebnitu ok I did some research now.

**Case 1** does not work, because it is required to provide a file ending.

**Case 2** is the expected behavior, node-sass-magic-importer and node-sass-glob-importer are supposed to import everything that matches the glob pattern, regardless if partial or not.

**Case 3** is a bug with node-sass-magic-importer – I created a new issue for this one: https://github.com/maoberlehner/node-sass-magic-importer/issues/158 Thank you for helping to uncover this bug.

Although what does work, for your use case, is using [node-sass-glob-importer](https://www.npmjs.com/package/node-sass-glob-importer)

I created the same directory structure you provided above and used the following import statement:

```scss
// imports.scss
@import 'blocks/**/[!_]*.scss';
```

```bash
node-sass --importer node_modules/node-sass-glob-importer/dist/cli.js -o dist src/imports.scss
```

Running the command above resulted in a file containing all the contents of `file-1.scss`, `file-2.scss`, `file-3.scss` and `menu.scss` but **not** `_menu_stack.scss`.

I've seen that you've already came up with another solution for your problem, but let me know if I can help you, If you're going back to using `node-sass-magic-importer` or `node-sass-glob-importer`.

Thanks for helping me finding https://github.com/maoberlehner/node-sass-magic-importer/issues/158, I'm closing this one because partial handling works as intended.

**Closed by maoberlehner** 2017-12-08 16:35 UTC
