### ISSUE TITLE
Import Error with .css extension

### ISSUE THREAD

**Issue by Oliphaunte** [maoberlehner/node-sass-magic-importer#162] opened 2018-01-17 06:29 UTC
Thanks for the great work on this importer! I recently moved from using the glob importer only, to the magic monorepo. Everything was working fine with the glob importer, but the monorepo throws the error below, with [root path] substituting the local relative path for brevity:

> It's not clear which file to import for 
> '@import "[root_path]/node_modules/slick-carousel/slick/slick"'.

> Candidates:
>   [root_path]/node_modules/slick-carousel/slick/slick.scss
>   [root_path]/node_modules/slick-carousel/slick/slick.css
> Please delete or rename all but one of these files.

I am currently importing two css files that throw the error, from the slick-carousel library like so:
> `@import "~slick-carousel/slick/slick.css";`
> `@import "~slick-carousel/slick/slick-theme.css";`

I tried also removing the `.css` extensions and also replacing them with `.scss`, but this causes the importer to get confused and to try and import every file extension ( .woff, .svg, etc.)

Based on the documentation, this seems like this shouldn't be an issue since I'm using the specific extension, but it seems like the importer is ignoring it? Just wondering if you might have any idea what the issue could be. Thank you again!

**Comment by maoberlehner** [comment] 2018-01-17 07:07
Hi @Oliphaunte, thanks for your nice feedback.

As far as I'm aware `Please delete or rename all but one of these files.` is coming from `node-sass` itself (it's definitely not a node-sass-magic-importer error message). 

The "problem" is this line in the code: https://github.com/maoberlehner/node-sass-magic-importer/commit/95355a08a21c38a1f751819a902f6a3c777137cb#diff-059fdd3e57fcb1cd204c64fda0fdf538R106

The reason why `.css` is stripped from the file URL is that `node-sass` does not import files ending in `.css`, instead it creates a native CSS import statement. But because thats rarely what you want, this module is stripping the `.css` ending. But by stripping it, `node-sass` does not know what file to import.

Importing the `.scss` file should work though, I'll look into this in the next few days.

**Comment by Oliphaunte** [comment] 2018-01-17 19:43
Thanks for the info! Yea, that makes sense. For further reference, when I use the `.scss` extension, the errors are for missing modules that are required inside the slick.scss file with non-css extensions, e.x:

`Module not found: Error: Can't resolve './fonts/slick.woff' in '[root_path]/app/assets/css'`
`Module not found: Error: Can't resolve './fonts/ajax-loader.gif' in '[root_path]/app/assets/css'`

Does this maybe have to do with the limitation for path resolving that's on the readme for the `node-sass-package-importer`?

Also, just to confirm, I'm currently using the monorepo in webpack in the sass-loader, just in case maybe I needed to do something further?

 i.e. : 
> loader: "sass-loader",
>   options: { 
>     importer: MagicImporter()
>   }

**Comment by Oliphaunte** [comment] 2018-01-17 19:59
Actually, just tried the `.scss` extension and reverting back to the glob-importer and the same error is occurring, so seems like it's either a node-sass or a webpack error. Not sure why .css works vs .scss, but will try to investigate further.

Anyways, pretty sure the issue isn't with the magic-importer, but node-sass, so I think this issue can be closed unless you think otherwise.

Sorry for the trouble!

**Comment by maoberlehner** [comment] 2018-01-18 07:23
No problem! After some quick tests, I think you'll need the https://github.com/bholloway/resolve-url-loader and configure it to load fonts and gifs. As you already pointed out, I also don't think the problem with importing the `.scss` file is related to `node-sass-magic-importer`.

The other "problem", which occurs in combination with loading the `.css` file, is not optimal, but more or less the expected behavior. So I'll close this issue, but feel free to create a new one or ask additional questions under this issue.

**Closed by maoberlehner** 2018-01-18 07:23 UTC
